CREATE TYPE "FindingSource" AS ENUM ('CRAWLSEO','SQUIRRELSCAN','PAGESPEED','GSC','DATAFORSEO');
CREATE TYPE "FindingCategory" AS ENUM ('SEO','TECHNICAL','PERFORMANCE','ACCESSIBILITY','SITE_INTEGRITY');
CREATE TYPE "FindingSeverity" AS ENUM ('CRITICAL','HIGH','MEDIUM','LOW','INFO');
CREATE TYPE "OpportunityPriority" AS ENUM ('CRITICAL','HIGH','MEDIUM','LOW');
CREATE TYPE "JobType" AS ENUM ('CRAWL_WEBSITE','RUN_AUDIT','CALCULATE_HEALTH','BUILD_OPPORTUNITIES','SYNC_GSC');
CREATE TYPE "JobStatus" AS ENUM ('QUEUED','CRAWLING','AUDITING','ANALYZING','COMPLETE','FAILED');
ALTER TABLE "Site" ADD COLUMN "clientId" TEXT;
CREATE TABLE "Organization" ("id" TEXT NOT NULL,"ownerId" TEXT NOT NULL,"name" TEXT NOT NULL DEFAULT 'FFS',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Client" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"businessName" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Client_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BusinessProfile" ("id" TEXT NOT NULL,"clientId" TEXT NOT NULL,"industry" TEXT NOT NULL,"primaryService" TEXT NOT NULL,"city" TEXT NOT NULL,"state" TEXT NOT NULL,"competitors" JSONB,CONSTRAINT "BusinessProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditFinding" ("id" TEXT NOT NULL,"siteId" TEXT NOT NULL,"crawlId" TEXT NOT NULL,"source" "FindingSource" NOT NULL,"ruleId" TEXT NOT NULL,"category" "FindingCategory" NOT NULL,"severity" "FindingSeverity" NOT NULL,"url" TEXT,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"evidence" JSONB,"remediation" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditFinding_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HealthScore" ("id" TEXT NOT NULL,"siteId" TEXT NOT NULL,"crawlId" TEXT NOT NULL,"overall" INTEGER NOT NULL,"seo" INTEGER NOT NULL,"technical" INTEGER NOT NULL,"performance" INTEGER NOT NULL,"accessibility" INTEGER NOT NULL,"siteIntegrity" INTEGER NOT NULL,"methodology" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "HealthScore_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GrowthOpportunity" ("id" TEXT NOT NULL,"siteId" TEXT NOT NULL,"crawlId" TEXT NOT NULL,"title" TEXT NOT NULL,"type" TEXT NOT NULL,"description" TEXT NOT NULL,"evidence" JSONB NOT NULL,"impactScore" INTEGER NOT NULL,"confidenceScore" INTEGER NOT NULL,"effortScore" INTEGER NOT NULL,"priorityScore" INTEGER NOT NULL,"priority" "OpportunityPriority" NOT NULL,"recommendedAction" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GrowthOpportunity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnalysisJob" ("id" TEXT NOT NULL,"siteId" TEXT NOT NULL,"crawlId" TEXT,"type" "JobType" NOT NULL,"status" "JobStatus" NOT NULL DEFAULT 'QUEUED',"startedAt" TIMESTAMP(3),"finishedAt" TIMESTAMP(3),"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AnalysisJob_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Organization_ownerId_name_key" ON "Organization"("ownerId","name");
CREATE INDEX "Client_organizationId_idx" ON "Client"("organizationId");
CREATE UNIQUE INDEX "BusinessProfile_clientId_key" ON "BusinessProfile"("clientId");
CREATE INDEX "Site_clientId_idx" ON "Site"("clientId");
CREATE INDEX "AuditFinding_siteId_severity_idx" ON "AuditFinding"("siteId","severity");
CREATE INDEX "AuditFinding_crawlId_idx" ON "AuditFinding"("crawlId");
CREATE UNIQUE INDEX "HealthScore_crawlId_key" ON "HealthScore"("crawlId");
CREATE INDEX "HealthScore_siteId_createdAt_idx" ON "HealthScore"("siteId","createdAt");
CREATE INDEX "GrowthOpportunity_siteId_priorityScore_idx" ON "GrowthOpportunity"("siteId","priorityScore");
CREATE INDEX "GrowthOpportunity_crawlId_idx" ON "GrowthOpportunity"("crawlId");
CREATE INDEX "AnalysisJob_siteId_createdAt_idx" ON "AnalysisJob"("siteId","createdAt");
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Client" ADD CONSTRAINT "Client_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BusinessProfile" ADD CONSTRAINT "BusinessProfile_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Site" ADD CONSTRAINT "Site_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditFinding" ADD CONSTRAINT "AuditFinding_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditFinding" ADD CONSTRAINT "AuditFinding_crawlId_fkey" FOREIGN KEY ("crawlId") REFERENCES "Crawl"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HealthScore" ADD CONSTRAINT "HealthScore_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HealthScore" ADD CONSTRAINT "HealthScore_crawlId_fkey" FOREIGN KEY ("crawlId") REFERENCES "Crawl"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GrowthOpportunity" ADD CONSTRAINT "GrowthOpportunity_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GrowthOpportunity" ADD CONSTRAINT "GrowthOpportunity_crawlId_fkey" FOREIGN KEY ("crawlId") REFERENCES "Crawl"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalysisJob" ADD CONSTRAINT "AnalysisJob_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalysisJob" ADD CONSTRAINT "AnalysisJob_crawlId_fkey" FOREIGN KEY ("crawlId") REFERENCES "Crawl"("id") ON DELETE CASCADE ON UPDATE CASCADE;
